### ISSUE TITLE
Should we be using a custom editor or Scratch 3.0?

### ISSUE THREAD

**Issue by MattTheNub** [elementnet/elementnet-editor#1]
@elementnet/editor Question: is it really that good of an idea to be using our own block rendering and stuff? I think we'd be much better off using Scratch 3.0

On the other hand, that would mean we would have to re-program it to work for us properly.

**Comment by radioblahaj** [comment]
We should use scratch 3.0. Scracth 3.0 uses Blocky.

**Comment by MattTheNub** [comment]
But... We would be rewriting quite a lot of the code anyway. The basic drag-and drop mechanics won't be that difficult to re-code. IIRC, that would also mean we have to be BSD-licensed rather than Apache

**Comment by radioblahaj** [comment]
Making our own Will Take a lot of time.
But, okay.
I will make a repo for this.
Can I have acces to create repos?

**Comment by MattTheNub** [comment]
@Narulacodes Repo for what? This *is* the editor repo...

**Comment by radioblahaj** [comment]
Opps. So how are we going to make this?

**Comment by MattTheNub** [comment]
SVG elements to render blocks, perhaps. For drag and drop, probably just [this](https://jqueryui.com/draggable/).

**Comment by radioblahaj** [comment]
How do we start this?

**Comment by MattTheNub** [comment]
I don't know. Right now, we are still in the process of fixing elementnet/elementnet-www

**Comment by radioblahaj** [comment]
What Do we need to fix?

**Comment by MattTheNub** [comment]
Organization. Take a look at other Node.JS projects. Root is clean, a few folders, and are built. I tried to do some of this on the `reorganize` branch, but it still needs to be fixed (both organization and the build)

**Comment by radioblahaj** [comment]
So, What files?

**Comment by MattTheNub** [comment]
We should also probably move this elsewhere (like Gitter)

**Comment by Narulacodes** [comment]
Okay

**Comment by Narulacodes** [comment]
I'm addingNitroCipher to our team
